// 📁 FILE TOOL — Generate, download, and export files from the agent
// Supports: code files, text/markdown reports, JSON/CSV data, HTML documents
// Uses chrome.downloads API to save files to the user's machine
// Can also compose files in-memory for other tools to consume

const STORAGE_KEY_FILE_LOG = 'handoff_file_log';
const MAX_FILE_LOG = 100;

// ── Types ───────────────────────────────────────────────────────────

export interface FileGenerateRequest {
  filename: string;
  content: string;
  mimeType?: string;
  openAfterDownload?: boolean;
}

export interface FileDownloadRequest {
  url: string;
  filename?: string;
  conflictAction?: 'uniquify' | 'overwrite' | 'prompt';
}

export interface FileResult {
  success: boolean;
  downloadId?: number;
  filename?: string;
  error?: string;
}

export interface FileLogEntry {
  id: string;
  timestamp: number;
  action: 'generate' | 'download' | 'export';
  filename: string;
  sizeBytes: number;
  mimeType: string;
  success: boolean;
  triggeredBy: 'agent' | 'user' | 'skill';
}

export type FileFormat = 'text' | 'json' | 'csv' | 'html' | 'markdown' | 'code' | 'xml';

// ── File Composers ──────────────────────────────────────────────────
// Build structured file content from data

export function composeJSON(data: unknown, pretty = true): string {
  return pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
}

export function composeCSV(headers: string[], rows: string[][]): string {
  const escapeCSV = (val: string) => {
    if (val.includes(',') || val.includes('"') || val.includes('\n')) {
      return `"${val.replace(/"/g, '""')}"`;
    }
    return val;
  };

  const headerLine = headers.map(escapeCSV).join(',');
  const dataLines = rows.map(row => row.map(escapeCSV).join(','));
  return [headerLine, ...dataLines].join('\n');
}

export function composeHTML(title: string, bodyContent: string, styles?: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #333; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #4CAF50; padding-bottom: 8px; }
    h2 { color: #2d2d2d; margin-top: 24px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f5f5f5; font-weight: 600; }
    pre { background: #f4f4f4; padding: 12px; border-radius: 4px; overflow-x: auto; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; color: #999; font-size: 0.85em; }
    ${styles || ''}
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${bodyContent}
  <div class="footer">Generated by HandOff &middot; ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

export function composeMarkdown(title: string, sections: { heading: string; content: string }[]): string {
  let md = `# ${title}\n\n`;
  md += `*Generated by HandOff — ${new Date().toLocaleString()}*\n\n---\n\n`;

  for (const section of sections) {
    md += `## ${section.heading}\n\n${section.content}\n\n`;
  }

  return md;
}

export function composeCodeFile(code: string, language: string, header?: string): string {
  const commentStyles: Record<string, [string, string]> = {
    javascript: ['//', ''],
    typescript: ['//', ''],
    python: ['#', ''],
    html: ['<!--', '-->'],
    css: ['/*', '*/'],
    sql: ['--', ''],
    shell: ['#', ''],
    ruby: ['#', ''],
    go: ['//', ''],
    rust: ['//', ''],
  };

  const [prefix, suffix] = commentStyles[language] || ['//', ''];
  const commentHeader = header
    ? `${prefix} ${header} ${suffix}\n${prefix} Generated by HandOff — ${new Date().toISOString()} ${suffix}\n\n`
    : '';

  return `${commentHeader}${code}`;
}

// ── MIME Type Detection ─────────────────────────────────────────────

const EXTENSION_MIME_MAP: Record<string, string> = {
  '.txt': 'text/plain',
  '.md': 'text/markdown',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.xml': 'application/xml',
  '.js': 'application/javascript',
  '.ts': 'text/typescript',
  '.py': 'text/x-python',
  '.css': 'text/css',
  '.sql': 'application/sql',
  '.sh': 'application/x-sh',
  '.yaml': 'text/yaml',
  '.yml': 'text/yaml',
  '.pdf': 'application/pdf',
  '.zip': 'application/zip',
};

function getMimeType(filename: string): string {
  const ext = filename.slice(filename.lastIndexOf('.')).toLowerCase();
  return EXTENSION_MIME_MAP[ext] || 'text/plain';
}

// ── File Tool Engine ────────────────────────────────────────────────

class FileToolEngine {
  private log: FileLogEntry[] = [];
  private initialized = false;

  async init(): Promise<void> {
    if (this.initialized) return;
    try {
      const result = await chrome.storage.local.get(STORAGE_KEY_FILE_LOG);
      this.log = result[STORAGE_KEY_FILE_LOG] || [];
      this.initialized = true;
      console.log(`[FileTool] Initialized: ${this.log.length} log entries`);
    } catch {
      this.initialized = true;
    }
  }

  // ── Generate & Download ───────────────────────────────────────────

  async generateFile(
    request: FileGenerateRequest,
    triggeredBy: 'agent' | 'user' | 'skill' = 'agent'
  ): Promise<FileResult> {
    await this.init();

    try {
      const mimeType = request.mimeType || getMimeType(request.filename);
      const contentSize = new TextEncoder().encode(request.content).length;
      const dataUrl = this.textToDataUrl(request.content, mimeType);

      const downloadId = await chrome.downloads.download({
        url: dataUrl,
        filename: request.filename,
        saveAs: false,
        conflictAction: 'uniquify',
      });

      await this.logAction({
        action: 'generate',
        filename: request.filename,
        sizeBytes: contentSize,
        mimeType,
        success: true,
        triggeredBy,
      });

      console.log(`[FileTool] Generated: ${request.filename} (${contentSize} bytes)`);

      return {
        success: true,
        downloadId,
        filename: request.filename,
      };
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : 'File generation failed';
      console.error(`[FileTool] Generate failed:`, error);

      await this.logAction({
        action: 'generate',
        filename: request.filename,
        sizeBytes: 0,
        mimeType: request.mimeType || 'unknown',
        success: false,
        triggeredBy,
      });

      return { success: false, error: errMsg };
    }
  }

  async downloadFile(
    request: FileDownloadRequest,
    triggeredBy: 'agent' | 'user' | 'skill' = 'agent'
  ): Promise<FileResult> {
    await this.init();

    try {
      const downloadId = await chrome.downloads.download({
        url: request.url,
        filename: request.filename,
        conflictAction: request.conflictAction || 'uniquify',
      });

      const filename = request.filename || request.url.split('/').pop() || 'download';

      await this.logAction({
        action: 'download',
        filename,
        sizeBytes: 0, // unknown until complete
        mimeType: 'unknown',
        success: true,
        triggeredBy,
      });

      console.log(`[FileTool] Downloaded: ${filename}`);
      return { success: true, downloadId, filename };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Download failed',
      };
    }
  }

  // ── Quick Generators ──────────────────────────────────────────────

  async exportJSON(data: unknown, filename = 'export.json'): Promise<FileResult> {
    return this.generateFile({
      filename,
      content: composeJSON(data),
      mimeType: 'application/json',
    });
  }

  async exportCSV(headers: string[], rows: string[][], filename = 'export.csv'): Promise<FileResult> {
    return this.generateFile({
      filename,
      content: composeCSV(headers, rows),
      mimeType: 'text/csv',
    });
  }

  async exportHTML(title: string, bodyContent: string, filename = 'report.html'): Promise<FileResult> {
    return this.generateFile({
      filename,
      content: composeHTML(title, bodyContent),
      mimeType: 'text/html',
    });
  }

  async exportMarkdown(title: string, sections: { heading: string; content: string }[], filename = 'report.md'): Promise<FileResult> {
    return this.generateFile({
      filename,
      content: composeMarkdown(title, sections),
      mimeType: 'text/markdown',
    });
  }

  async exportCode(code: string, filename: string, language = 'javascript'): Promise<FileResult> {
    return this.generateFile({
      filename,
      content: composeCodeFile(code, language),
    });
  }

  // ── Logging ───────────────────────────────────────────────────────

  private async logAction(entry: Omit<FileLogEntry, 'id' | 'timestamp'>): Promise<void> {
    const logEntry: FileLogEntry = {
      ...entry,
      id: `fl_${Date.now()}`,
      timestamp: Date.now(),
    };

    this.log.push(logEntry);
    if (this.log.length > MAX_FILE_LOG) {
      this.log = this.log.slice(-MAX_FILE_LOG);
    }

    await chrome.storage.local.set({ [STORAGE_KEY_FILE_LOG]: this.log });
  }

  async getLog(limit = 30): Promise<FileLogEntry[]> {
    await this.init();
    return this.log.slice(-limit);
  }

  async clearLog(): Promise<void> {
    this.log = [];
    await chrome.storage.local.remove(STORAGE_KEY_FILE_LOG);
  }

  // ── Helpers ───────────────────────────────────────────────────────

  // Service-worker-safe data URL creation (FileReader is NOT available in MV3 workers)
  private textToDataUrl(content: string, mimeType: string): string {
    // Encode to base64 — handles ASCII; for unicode we encode to UTF-8 first
    const utf8Bytes = new TextEncoder().encode(content);
    let binary = '';
    for (let i = 0; i < utf8Bytes.length; i++) {
      binary += String.fromCharCode(utf8Bytes[i]);
    }
    const base64 = btoa(binary);
    return `data:${mimeType};base64,${base64}`;
  }

  formatForPrompt(result: FileResult): string {
    if (!result.success) {
      return `\n[FILE OPERATION FAILED]: ${result.error}\n`;
    }
    return `\n[FILE SAVED]: ${result.filename} (download ID: ${result.downloadId})\n`;
  }

  getStats(): { totalFiles: number; generated: number; downloaded: number } {
    const generated = this.log.filter(e => e.action === 'generate').length;
    const downloaded = this.log.filter(e => e.action === 'download').length;
    return {
      totalFiles: this.log.length,
      generated,
      downloaded,
    };
  }
}

// Singleton
export const fileTool = new FileToolEngine();
